navigators = {
    "RASIS": {
        "Everlasting Message",
        "Find the Answer",
        "FLügeL《Λrp:ΣggyØ》",
        "INDEPENDENT SKY",
        "Lord=Crossight",
        "Ops:Code-Rapture-",
        "Prayer",
        "Sounds Of Summer",
        "#Endroll",
        "VOLTEXES III",
        "XROSS THE XOUL",
        "Destiny",
        "Fly Like You",
        "Goddess Bless you",
        "HEAVENLY SMILE",
        "I",
        "iLLness LiLin",
        "VOLTEXES IV",
        "Innocent",
        "LECTORIA",
        "Teufel",
        "VIVIDWAVERS",
        "月光乱舞",
        "いつかの夢、またねの約束。",
        "君がいる場所へ",
        "セイレーン ～悲壮の竪琴～",
        "Aurolla",
        "Believe (y)our Wings {V:IVID RAYS}",
    },
    "GRACE": {
        "DIABLOSIS::Nāga",
        "#Endroll",
        "FLügeL《Λrp:ΣggyØ》",
        "INDEPENDENT SKY",
        "Lachryma《Re:Queen’M》",
        "NEO TREASON",
        "Ops:Code-Rapture-",
        "REGALIA",
        "relegation grimoire",
        "veRtrageS",
        "グレイスちゃんの超～絶!!グラビティ講座w",
        "いつかの夢、またねの約束。",
        "君がいる場所へ",
        "Nexta",
        "Reb∞t",
        "《Re:miniscence》",
        "Cross Fire",
        "crossing blue",
        "Divine's:Bugscript",
        "Goddess Bless you",
        "HEAVENLY SMILE",
        "iLLness LiLin",
        "ULTiMATE INFLATiON",
        "朧 (kamome sano remix)",
        "Aurolla",
        "Believe (y)our Wings {GRA5P WAVES}",
        "BLIZZARD BEAT",
        "D1g1t1ze b0dy",
        "Innocent",
        "scary night",
        "Teufel",
        "VIVIDWAVERS",
        "ミュージックプレイヤー",
        "MixxioN",
        "Resonant Gear",
        "SuddeИDeath",
        "VALKYRIE ASSAULT",
        "夢の終わり、世界のはじまり。",
    },
    "Tsumabuki Left": {
        "croiX",
        "Gott",
        "Fiat Lux",
        "Last Battalion",
        "Princessどうかお願い!!",
        "Survival Games (Hommarju Remix)",
        "TrailBlazer",
        "超越してしまった彼女と其を生み落した理由",
        'コンベア速度Max!? しゃいにん☆廻転ズシ"Sushi&Peace"',
        "隅田川夏恋歌 (I/O Angel mix)",
        "ボルテ体操第一",
        "Destroy",
        "Get back here",
        "INF-B《L-aste-R》",
        "LegenD.",
        "NEO TREASON",
        "Twin Blaster",
        "Violet Soul",
        "君がいる場所へ",
        "↓↓↓",
        "ΣmbryØ",
        "Fin.ArcDeaR",
        "Last Resort",
        "Mirrorwall",
        "Rebuilding of Paradise Lost",
        "Aurolla",
        "GEMINI LA2ER",
        "SociuS",
        "V Sen5eS",
        "I Left for my Right",
        "PLANISPHERE",
        "refluxio",
    },
    "Tsumabuki Right": {
        "croiX",
        "Gott",
        "TYCOON",
        "Fiat Lux",
        "Hellfire",
        "Last Battalion",
        "Last Concerto",
        "Survival Games (Hommarju Remix)",
        "TrailBlazer",
        "隅田川夏恋歌 (I/O Angel mix)",
        "ボルテ体操第一",
        "2 MINUTES FIGHTERS",
        "Destroy",
        "Discloze",
        "Get back here",
        "IKAROS DYNAMITE!!!!",
        "Liming Light",
        "Twin Blaster",
        "Violet Soul",
        "君がいる場所へ",
        "Over The Top",
        "A Lasting Promise",
        "Absolute Domination",
        "ΣmbryØ",
        "Fin.ArcDeaR",
        "Juggler's Maddness",
        "Rebuilding of Paradise Lost",
        "準備運動",
        "Aurolla",
        "GEMINI LA2ER",
        "SociuS",
        "V Sen5eS",
        "Wings to fly high",
    },
    "NEAR & NOAH": {
        "freaky freak",
        "choux à la crème",
        "concon (picom'n'bass rmx)",
        "Dawn of Asia",
        "Wish upon Twin Stars",
        "archive::zip",
        "Follow Up",
        "Happy Sensation",
        "Milkyway - memorable -",
        "トリコロール・ダイアリー",
        "tricky trick",
        "Twin Rocket",
        "Aurolla",
        "FIN4LE ～終止線の彼方へ～",
        "HE4VEN ～天国へようこそ～",
        "光射す澪のユズリハ",
        "Яe:son D'être",
        "ultra turbo",
        "星の透る夏空に願う",
        "君は Fantasista",
        "Fun walk!!",
        "sparky spark",
    },
    "Kureha": {
        "Absurd Gaff",
        "good high school",
        "CODE -CRiMSON-",
        "Smile",
        "AYAKASHI",
        "Celestial stinger",
        "EMPIRE OF FLAME",
        "Nofram",
        "Poison Blood",
        "Warriors Aboot",
        "感情Xerography",
        "紅の剣舞",
        "Nexta",
        "Arcade Prison",
        "Cy-Bird",
        "逆月",
        "666",
        "伊邪那美白山姫大神",
        "Enter The Rave",
        "Little Red Riding Hood",
        "灼ナル刃、破カヰ譜",
        "運命超過乃巡合",
    },
    "Hina, Ao, Momo": {
        "TYCOON",
        "バタフライキャット",
        "concon (picom'n'bass rmx)",
        "Wuv U -More2 HAPPY Re-Mix Special-",
        "crêpe suzette",
        "CUTIE☆EX-DREAM",
        "eternita",
        "Ok!! Hug Me",
        "Wuv U (Colorful QT3 nekomix)",
        "Wuv U(pico/ustic rmx)",
        "ちぇいす いん ざ さんしゃいん！！！",
        "きらきらタイム☆",
        "トリコロール・ダイアリー",
        "Ring！Run！Nyan!!",
        "Poppin’Cats!!",
        "Staring at star",
        "ULTRAVELOCITY",
        "Aurolla",
        "プラネタジャーニー",
        "ホワイトパレード",
        "SuperMiracleEnsemble",
        "Grandeur",
        "party:stage",
        "Puni Puni Parade",
    },
    "Voltenizer Maxima": {
        "FLOWER REDALiCE Remix",
        "Max Burning!!",
        "Bangin' Burst",
        "Growth Memories",
        "XROSS INFECTION",
        "ボルテ体操第一",
        "REVOLVER",
        "UnivEarth",
        "World's end",
        "極圏",
        "マサカリブレイド",
        "GODHEART",
        "Immortal saga",
        "TWO-TORIAL",
        "Xéroa",
        "Xronièr",
        "Aurolla",
        "マキシマ先生の満開!!ヘヴンリー講座♥",
        "All for One",
        "FEEL THE FORCE",
        "Perfect Ultimate Celebration!!",
        "X1GNUS",
    },
    "Kougei Ciel Nana": {
        "ナナイロ",
        "Appliqué",
        "Demise Quartet",
        "Le Fruit Défendu",
        "Le ××××",
        "Sourire",
        "The star in eclipse",
        "Liar rain",
        "Grand-Guignol",
        "神話に芽吹く",
        "祝福の色彩は想い結ぶ君たち迄",
        "真夏の海の修道女",
        "雲海",
        "HeaveИ's Rain",
        "Souhait bleu",
        "極夜、暁を望んで",
    },
    "Kanade Yamashina": {
        "じゅーじゅー♥焼肉の火からフェニックス！？～再誕の†炭火焼き～",
        "ヤサイマシ☆ニンニクアブラオオメ",
        'コンベア速度Max!? しゃいにん☆廻転ズシ"Sushi&Peace"',
        "ませまてぃっく♡ま＋ま＝まじっく！　～徹夜の追込みエナジーまっくす！～",
        "混乱少女♥そふらんちゃん!!",
        "*Feels Seasickness...*",
        "JUNKIE FLAVOR",
        "超☆超☆光☆速☆出☆前☆最☆速!!! スピード★スター★かなで",
        "Voice 7 Voice!!!!!!!",
        "まみむめ🍄まるっと🍄まっしゅるーむ🍄🍄",
        "ばらんが!!!!",
        "ゔぉるみっくす!!!!",
    },
    "Lyric Rishuna": {
        "Gorgetech",
        "VVelcome!!",
        "Chakra",
        "いでぃおで結構！",
    },
    "TAMA-chan & TAMANEKO": {
        "Space Diver Tama",
        "大宇宙ステージ",
        "Goodbye-bye Planet",
        "Hyper☆Chipspace",
        "Pon-Pon-Pompoko Dai-Sen-Saw!",
        "Sayonara Planet Wars",
        "I",
        "Made In Love",
        "#SpeedyCats",
        "Poppin’Cats!!",
        "Aurolla",
        "GaLaXyEggPlanT",
        "Sudden Visitor",
        "Initiating League",
        "Never Forget Evergreen",
        "Test Flight",
    },
}
